### ISSUE TITLE
Написать ручки на удаление/обновление сессий и пользователей

### ISSUE THREAD

**Issue by KatySolo** [KatySolo/realtimepoll_server#23]
Нужны ручки для KatySolo/realtimepollreact#31 

При удалении опроса, пользователь-лектор остается.
При удалении пользователя, опрос, где был этот пользователь лектором, удаляется.

**Comment by KatySolo** [comment]
> Кстати возникает вопрос, если мы удаляем пользователя, то все лекции, которые он проводил, тоже должны быть удалены?

Да, думаю это будет правильно в этой ситуации, обновлю описание задачки.

**Comment by JulieBlack666** [comment]
Ещё можно уточнить, при обновлении, что мы хотим уметь менять? Я пока вижу так, что у пользователя менять только имя в принципе, а у сессии можно название и даты старта и финиша. Хотя можно было бы у сессии менять лектора, а у пользователя сессии, но мне кажется это поведение не самым лучшим, наверное🤔

**Comment by JulieBlack666** [comment]
Понимаю, что обновление пока в верстку вряд ли поедет, но всё равно лучше сразу всё предусмотреть

**Comment by KatySolo** [comment]
> Хотя можно было бы у сессии менять лектора, а у пользователя сессии

Лектора - да, можно сделать перезаписью текущего, а у пользователя сессии не нужно, это излишне, тем более у нас нет функционала вывода данных по пользователю.

**Comment by KatySolo** [comment]
> Хотя можно было бы у сессии менять лектора, а у пользователя сессии

Лектора - да, можно сделать перезаписью текущего, а у пользователя сессии не нужно, это излишне, тем более у нас нет функционала вывода данных по пользователю.
